[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8,<9"]
build-backend = "setuptools.build_meta"

[project]
name = 'clyent'
dynamic = ["version"]

[tool.setuptools_scm]
version_file = "clyent/_version.py"

[tool.isort]
profile = 'black'